version: '3.8'

services:
  relative_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: relative_db
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

  graph_db:
    image: neo4j
    container_name: graph_db
    restart: always
    ports:
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
    networks:
      - app-network

  document_db:
    image: mongo
    restart: always
    container_name: document_db
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@document_db:27017/
      ME_CONFIG_BASICAUTH: false
  frontend:
    container_name: 'frontend'
    image: frontend
    ports:
      - "80:80"
    restart: always
    
networks:
  app-network:
    driver: bridge
