name: .NET Core Full Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Build Job
  build_backend:
    runs-on: ubuntu-latest

    env:
      Solution_Name: Backend.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run:  dotnet restore 

    - name: Build Solution
      run: dotnet build --configuration Release
      
    - name: Execute unit tests
      run: dotnet test UnitTests/UnitTests.csproj

    - name: Build Docker Image
      run: |
        docker build . \
          -f dockerfile.api \
          -t bjand49/tonl-api:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: bjand49
        password: ${{ secrets.DOCKER_PAT }}

    - name: Push Docker Image
      run: docker push bjand49/tonl-api


  build_seeder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache NuGet Packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('DataSeeder/**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build Docker Image
      run: |
        docker build . \
          -f dockerfile.seeder \
          -t bjand49/tonl-seeder:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: bjand49
        password: ${{ secrets.DOCKER_PAT }}

    - name: Push Docker Image
      run: docker push bjand49/tonl-seeder


  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file dockerfile.frontend --tag bjand49/tonl-frontend
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: bjand49
        password: ${{ secrets.DOCKER_PAT }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: bjand49/tonl-frontend
        
    - name: Push Docker image
      run: docker push bjand49/tonl-frontend

  build_relational_migrator:
    runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet Packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('Migrators/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build Docker Image
        run: |
          docker build . \
            -f dockerfile.migrator.relational \
            -t bjand49/tonl-migrator-relational:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: bjand49
          password: ${{ secrets.DOCKER_PAT }}

      - name: Push Docker Image
        run: docker push bjand49/tonl-migrator-relational
