name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish Application
      run: dotnet publish -c Release -o ./published

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tonl-api # Replace with your Web App name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./published # Path to the output directory
