name: .NET Core Full Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Build Job
  build_backend:
    runs-on: ubuntu-latest

    env:
      Solution_Name: Backend.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run:  dotnet restore 

    - name: Build Solution
      run: dotnet build --configuration Release
      
    - name: Execute unit tests
      run: dotnet test UnitTests/UnitTests.csproj

    - name: Build the Docker image
      run: docker build . --file dockerfile.api --tag bjand49/tonl-api
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: bjand49
        password: ${{ secrets.DOCKER_PAT }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: bjand49/tonl-api
        
    - name: Push Docker image
      run: docker push bjand49/tonl-api
