name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  
                             

    env:
      Solution_Name: Backend.sln                         
      Test_Project_Path: UnitTests/UnitTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Test
      run: ls
#    - name: Execute unit tests
#      run: dotnet test UnitTests/UnitTests.csproj
    - name: Deploy Backend in Background
      run: Start-Process -FilePath "dotnet" -ArgumentList "run --project Backend/Backend.csproj" -NoNewWindow -PassThru


      
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
